print("hello world!")
print("Day 1 - Python Print Function")
print("The function is declared like this:")
print("print('what to print')")
print("Hello world!\nHello world!")
print("Hello" + " " + "janet")
print("Day 1 -string manipulation")
print('string concatenation is done with the "+" sign.')
print("e.g.print('Hello" + " world!')")
print("New lines can be created with a backslash and n.")
print("Hello"  + " " + input("What is your name?"))
name=input("What is your name? ")
print(len(name))
name="jack"
print(name)
name="janet"
print(name)
name=input("What is your name")
lenght=len(name)
print(lenght)
a =input("a:")
b =input("b:")
c = a
print("Welcome to the band name calculator")
city = input("Which city did you grow up in?\n ")
print(city)
pet = input("What is the name of a pet\n")
print("Your band name could be " + city + "" + pet)


